USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE SAAS_WH
WITH 
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE SAAS_DB;

USE DATABASE SAAS_DB;

CREATE SCHEMA RAW;
CREATE SCHEMA STAGING;
CREATE SCHEMA MART;

USE ROLE ACCOUNTADMIN;

CREATE ROLE SAAS_ENGINEER;

GRANT USAGE ON WAREHOUSE SAAS_WH TO ROLE SAAS_ENGINEER;
GRANT USAGE ON DATABASE SAAS_DB TO ROLE SAAS_ENGINEER;

GRANT USAGE ON ALL SCHEMAS IN DATABASE SAAS_DB TO ROLE SAAS_ENGINEER;

GRANT CREATE TABLE ON ALL SCHEMAS IN DATABASE SAAS_DB TO ROLE SAAS_ENGINEER;

GRANT SELECT, INSERT, UPDATE, DELETE 
ON ALL TABLES IN DATABASE SAAS_DB 
TO ROLE SAAS_ENGINEER;

GRANT ROLE SAAS_ENGINEER TO USER AHUSS1;

USE ROLE SAAS_ENGINEER;

USE ROLE SAAS_ENGINEER;
USE WAREHOUSE SAAS_WH;
USE DATABASE SAAS_DB;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE customers_raw (
    customer_id INTEGER,
    first_name STRING,
    last_name STRING,
    email STRING,
    country STRING,
    signup_date DATE
);

CREATE OR REPLACE TABLE subscriptions_raw (
    subscription_id INTEGER,
    customer_id INTEGER,
    plan_id INTEGER,
    start_date DATE,
    end_date DATE
);

CREATE OR REPLACE TABLE payments_raw (
    payment_id INTEGER,
    customer_id INTEGER,
    plan_id INTEGER,
    payment_date DATE,
    amount NUMBER(10,2)
);

CREATE OR REPLACE TABLE usage_raw (
    customer_id INTEGER,
    usage_date DATE,
    actions_performed INTEGER
);

CREATE OR REPLACE STAGE saas_stage;

USE ROLE ACCOUNTADMIN;

GRANT CREATE STAGE ON SCHEMA SAAS_DB.RAW TO ROLE SAAS_ENGINEER;

USE ROLE SAAS_ENGINEER;

CREATE OR REPLACE STAGE saas_stage;

PUT file:///Users/aneeqhussain/Documents/saas_analytics_project/data/customers.csv @saas_stage;
PUT file:///Users/aneeqhussain/Documents/saas_analytics_project/data/subscriptions.csv @saas_stage;
PUT file:///Users/aneeqhussain/Documents/saas_analytics_project/data/payments.csv @saas_stage;
PUT file:///Users/aneeqhussain/Documents/saas_analytics_project/data/usage.csv @saas_stage;

COPY INTO customers_raw
FROM @saas_stage/customers.csv
FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1);

COPY INTO subscriptions_raw
FROM @saas_stage/subscriptions.csv
FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1);

COPY INTO payments_raw
FROM @saas_stage/payments.csv
FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1);

COPY INTO usage_raw
FROM @saas_stage/usage.csv
FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1);

SELECT COUNT(*) FROM customers_raw;
SELECT COUNT(*) FROM subscriptions_raw;
SELECT COUNT(*) FROM payments_raw;
SELECT COUNT(*) FROM usage_raw;

SELECT CURRENT_ROLE();

USE ROLE ACCOUNTADMIN;

GRANT USAGE ON DATABASE SAAS_DB TO ROLE SAAS_ENGINEER;

GRANT USAGE ON SCHEMA SAAS_DB.STAGING TO ROLE SAAS_ENGINEER;

GRANT CREATE TABLE ON SCHEMA SAAS_DB.STAGING TO ROLE SAAS_ENGINEER;

GRANT CREATE VIEW ON SCHEMA SAAS_DB.STAGING TO ROLE SAAS_ENGINEER;

GRANT USAGE ON WAREHOUSE SAAS_WH TO ROLE SAAS_ENGINEER;

USE ROLE SAAS_ENGINEER;

SELECT CURRENT_ROLE();

SELECT * FROM SAAS_DB.STAGING.stg_customers LIMIT 10;

SELECT * FROM SAAS_DB.STAGING.mrr;

USE WAREHOUSE COMPUTE_WH;
ALTER WAREHOUSE COMPUTE_WH RESUME;